#ifndef _CONSTANTS_DREAM_TEAM_GUARD
#define _CONSTANTS_DREAM_TEAM_GUARD

#define NAME_LENGTH 50
#define ADRESS_LENGTH 70
#define EMAIL_LENGTH 50
#define PASSWORD_SIGNED_LENGTH 50
#define DATE_LEHGTH 10

#endif
